# Generated by Django 3.1.4 on 2021-01-13 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BujoneUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.TextField(max_length=400)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('bujoneuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bujoneuser')),
            ],
        ),
        migrations.CreateModel(
            name='JournalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.TextField(blank=True, max_length=400, null=True)),
                ('bujoneuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bujoneuser')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('bujoneuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bujoneuser')),
            ],
        ),
    ]
