# Generated by Django 3.1.4 on 2021-01-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
