# Generated by Django 3.1.4 on 2021-01-14 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210113_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalmodel',
            name='bujoneuser',
        ),
        migrations.AddField(
            model_name='journalmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
