# Generated by Django 3.1.4 on 2021-01-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210114_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
