# Generated by Django 3.1.4 on 2021-01-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210114_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BujoneUser',
        ),
    ]
